### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by riongull** [dashhive/dash-daypass#8]
- [x] Phone call between Amanda, AJ, and Rion to discuss roadmap (1 DASH)
- [ ] Review and complete existing [Issues](https://github.com/dashhive/dash-daypass/issues) and [PRs](https://github.com/dashhive/dash-daypass/pulls) (4 DASH)
- [ ] Update CSS so paywall covers developer-chosen HTML element instead of the page body (4 DASH)
